AWSTemplateFormatVersion: 2010-09-09
Resources:
  PasswordsUserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: PasswordsUsers
      AutoVerifiedAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
      Schema:
        - AttributeDataType: String
          Mutable: true
          Name: email
          Required: true
      UsernameAttributes:
        - email
  PasswordsUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref PasswordsUserPool
      SupportedIdentityProviders:
        - COGNITO
      PreventUserExistenceErrors: ENABLED
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
    DependsOn:
      - PasswordsUserPool
  PasswordsUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: csci5409
      UserPoolId: !Ref PasswordsUserPool
    DependsOn:
      - PasswordsUserPoolClient
  MySecret1:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: PasswordsUserPoolID
      Description: user pool id
      SecretString: !Ref PasswordsUserPool
    DependsOn:
      - PasswordsUserPool
  MySecret2:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: PasswordsUserPoolClientID
      Description: user pool id
      SecretString: !Ref PasswordsUserPoolClient
    DependsOn:
      - PasswordsUserPool
